"""네 개 고정 HWPX 양식에 대한 DB 컬럼 → XML 셀 규칙."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

CellOperation = Literal[
    "set",
    "append",
    "prepend",
    "prepend_line",
    "replace",
    "checkbox",
]


@dataclass(frozen=True)
class XmlCellRule:
    """하나의 외부 컬럼을 HWPX section XML 셀에 연결한다."""

    source_key: str
    table_index: int
    row: int
    column: int
    operation: CellOperation = "set"
    marker: str | None = None
    replacement_format: str | None = None
    record_keys: tuple[str, ...] = ()
    text_index: int | None = None
    digits_only: bool = False
    value_index: int | None = None


TEMPLATE_RULES: dict[str, tuple[XmlCellRule, ...]] = {
    "identity_guaranty_v129": (
        XmlCellRule("foreign_family_name", 0, 3, 1, "append"),
        XmlCellRule(
            "foreign_given_name",
            0,
            3,
            2,
            "append",
            record_keys=("foreign_name",),
        ),
        XmlCellRule("foreign_name_hanja", 0, 3, 5, "append"),
        XmlCellRule("foreign_birthdate", 0, 4, 1, "append"),
        XmlCellRule(
            "foreign_male",
            0,
            4,
            7,
            "checkbox",
            marker="[  ]남",
            replacement_format="[v]남",
        ),
        XmlCellRule(
            "foreign_female",
            0,
            4,
            7,
            "checkbox",
            marker="[  ]여",
            replacement_format="[v]여",
        ),
        XmlCellRule(
            "foreign_nationality",
            0,
            5,
            1,
            "append",
            record_keys=("worker.nationality",),
        ),
        XmlCellRule("foreign_passport", 0, 5, 5, "append"),
        XmlCellRule("foreign_korea_address", 0, 6, 1, "append"),
        XmlCellRule(
            "foreign_phone",
            0,
            6,
            5,
            "append",
            record_keys=("worker.phone",),
        ),
        XmlCellRule("stay_purpose", 0, 7, 1, "append"),
        XmlCellRule("guarantor_name", 0, 10, 1, "append"),
        XmlCellRule("guarantor_name_hanja", 0, 10, 5, "append"),
        XmlCellRule("guarantor_nationality", 0, 11, 1, "append"),
        XmlCellRule(
            "guarantor_male",
            0,
            11,
            7,
            "checkbox",
            marker="[  ]남",
            replacement_format="[v]남",
        ),
        XmlCellRule(
            "guarantor_female",
            0,
            11,
            7,
            "checkbox",
            marker="[  ]여",
            replacement_format="[v]여",
        ),
        XmlCellRule("guarantor_passport_or_birthdate", 0, 12, 1, "append"),
        XmlCellRule("guarantor_phone", 0, 12, 5, "append"),
        XmlCellRule("guarantor_address", 0, 13, 1, "append"),
        XmlCellRule("relationship", 0, 14, 1, "append"),
        XmlCellRule(
            "workplace",
            0,
            15,
            1,
            "append",
            record_keys=("company.name",),
        ),
        XmlCellRule("position", 0, 15, 5, "append"),
        XmlCellRule("workplace_address", 0, 16, 1, "append"),
        XmlCellRule("guarantee_period", 0, 17, 1, "append"),
        XmlCellRule("guarantee_date", 0, 21, 0),
        XmlCellRule(
            "signature_guarantor_name",
            0,
            22,
            4,
            record_keys=("guarantor_name",),
        ),
    ),
    "employment_extension_application_v12_3": (
        XmlCellRule(
            "workplace_name",
            0,
            5,
            0,
            "append",
            record_keys=("company.name",),
        ),
        XmlCellRule("workplace_phone", 0, 5, 11, "append"),
        XmlCellRule("workplace_address", 0, 6, 0, "append"),
        XmlCellRule("representative", 0, 6, 11, "append"),
        XmlCellRule("business_type", 0, 7, 0, "append"),
        XmlCellRule("business_number", 0, 7, 11, "append"),
        XmlCellRule(
            "check_eligible_industry",
            0,
            9,
            4,
            "checkbox",
            marker="[  ]외국인근로자 도입 업종에 해당",
            replacement_format="[v]외국인근로자 도입 업종에 해당",
        ),
        XmlCellRule(
            "check_no_adjustment_dismissal",
            0,
            9,
            4,
            "checkbox",
            marker=(
                "[  ]취업기간 만료자 재취업활동 기간 연장 신청일 2개월 전부터 "
                "고용허가서 발급일까지 내국인근로자를 고용조정으로 이직시키지 않았음"
            ),
            replacement_format=(
                "[v]취업기간 만료자 재취업활동 기간 연장 신청일 2개월 전부터 "
                "고용허가서 발급일까지 내국인근로자를 고용조정으로 이직시키지 않았음"
            ),
        ),
        XmlCellRule(
            "check_no_unpaid_wages",
            0,
            9,
            4,
            "checkbox",
            marker=(
                "[  ]취업기간 만료자 재취업활동 기간 연장 신청일 5개월 전부터 "
                "고용허가서 발급일까지 임금체불이 없음"
            ),
            replacement_format=(
                "[v]취업기간 만료자 재취업활동 기간 연장 신청일 5개월 전부터 "
                "고용허가서 발급일까지 임금체불이 없음"
            ),
        ),
        XmlCellRule(
            "check_insurance",
            0,
            9,
            4,
            "checkbox",
            marker="[  ]고용보험 및 산업재해보상보험 가입",
            replacement_format="[v]고용보험 및 산업재해보상보험 가입",
        ),
        XmlCellRule(
            "check_departure_guarantee",
            0,
            9,
            4,
            "checkbox",
            marker=(
                "[  ]이미 고용한 외국인근로자에 대한 출국만기보험등 및 "
                "보증보험 가입"
            ),
            replacement_format=(
                "[v]이미 고용한 외국인근로자에 대한 출국만기보험등 및 "
                "보증보험 가입"
            ),
        ),
        XmlCellRule(
            "employee_1_serial",
            0,
            13,
            0,
            record_keys=("worker.employee_no",),
        ),
        XmlCellRule(
            "employee_1_name",
            0,
            13,
            1,
            record_keys=("worker.legal_name",),
        ),
        XmlCellRule("employee_1_resident_number", 0, 13, 4),
        XmlCellRule(
            "employee_1_nationality",
            0,
            13,
            7,
            record_keys=("worker.nationality",),
        ),
        XmlCellRule("employee_1_passport_number", 0, 13, 9),
        XmlCellRule(
            "employee_1_expiry_date",
            0,
            13,
            13,
            record_keys=("worker.stay_expiry",),
        ),
        XmlCellRule("application_date", 0, 20, 0),
        XmlCellRule(
            "applicant_name",
            0,
            21,
            0,
            "replace",
            marker="신청인               ",
            replacement_format="신청인  {value}",
        ),
        XmlCellRule("submission_authority", 0, 22, 0),
        XmlCellRule(
            "consent_applicant_name",
            0,
            29,
            14,
            record_keys=("applicant_name",),
        ),
    ),
    "immigration_integrated_application_v34": (
        XmlCellRule(
            "application_foreign_registration",
            0,
            4,
            0,
            "checkbox",
            marker="[  ]",
            replacement_format="[v]",
            text_index=0,
        ),
        XmlCellRule(
            "application_activity_permission",
            0,
            4,
            14,
            "checkbox",
            marker="[  ]",
            replacement_format="[v]",
            text_index=0,
        ),
        XmlCellRule(
            "application_card_reissue",
            0,
            6,
            0,
            "checkbox",
            marker="[  ]",
            replacement_format="[v]",
            text_index=0,
        ),
        XmlCellRule(
            "application_workplace_change",
            0,
            6,
            14,
            "checkbox",
            marker="[  ]",
            replacement_format="[v]",
            text_index=0,
        ),
        XmlCellRule(
            "application_stay_extension",
            0,
            7,
            0,
            "checkbox",
            marker="[  ]",
            replacement_format="[v]",
            text_index=0,
        ),
        XmlCellRule(
            "application_reentry",
            0,
            7,
            14,
            "checkbox",
            marker="[  ]",
            replacement_format="[v]",
            text_index=0,
        ),
        XmlCellRule(
            "application_status_change",
            0,
            8,
            0,
            "checkbox",
            marker="[  ]",
            replacement_format="[v]",
            text_index=0,
        ),
        XmlCellRule(
            "application_address_change",
            0,
            8,
            14,
            "checkbox",
            marker="[  ]",
            replacement_format="[v]",
            text_index=0,
        ),
        XmlCellRule(
            "application_status_grant",
            0,
            10,
            0,
            "checkbox",
            marker="[  ]",
            replacement_format="[v]",
            text_index=0,
        ),
        XmlCellRule(
            "application_information_change",
            0,
            10,
            14,
            "checkbox",
            marker="[  ]",
            replacement_format="[v]",
            text_index=0,
        ),
        XmlCellRule("family_name", 0, 14, 3),
        XmlCellRule("given_names", 0, 14, 19),
        XmlCellRule("birth_year", 0, 16, 5),
        XmlCellRule("birth_month", 0, 16, 15),
        XmlCellRule("birth_day", 0, 16, 19),
        XmlCellRule(
            "sex_male",
            0,
            15,
            31,
            "checkbox",
            marker="[ ]남 M",
            replacement_format="[v]남 M",
        ),
        XmlCellRule(
            "sex_female",
            0,
            15,
            31,
            "checkbox",
            marker="[ ]여 F",
            replacement_format="[v]여 F",
        ),
        XmlCellRule(
            "nationality",
            0,
            15,
            44,
            record_keys=("worker.nationality",),
        ),
        XmlCellRule(
            "foreign_registration_digit_1",
            0,
            17,
            9,
            record_keys=("foreign_registration_number",),
            digits_only=True,
            value_index=0,
        ),
        XmlCellRule(
            "foreign_registration_digit_2",
            0,
            17,
            11,
            record_keys=("foreign_registration_number",),
            digits_only=True,
            value_index=1,
        ),
        XmlCellRule(
            "foreign_registration_digit_3",
            0,
            17,
            15,
            record_keys=("foreign_registration_number",),
            digits_only=True,
            value_index=2,
        ),
        XmlCellRule(
            "foreign_registration_digit_4",
            0,
            17,
            16,
            record_keys=("foreign_registration_number",),
            digits_only=True,
            value_index=3,
        ),
        XmlCellRule(
            "foreign_registration_digit_5",
            0,
            17,
            19,
            record_keys=("foreign_registration_number",),
            digits_only=True,
            value_index=4,
        ),
        XmlCellRule(
            "foreign_registration_digit_6",
            0,
            17,
            21,
            record_keys=("foreign_registration_number",),
            digits_only=True,
            value_index=5,
        ),
        XmlCellRule(
            "foreign_registration_digit_7",
            0,
            17,
            24,
            record_keys=("foreign_registration_number",),
            digits_only=True,
            value_index=6,
        ),
        XmlCellRule(
            "foreign_registration_digit_8",
            0,
            17,
            26,
            record_keys=("foreign_registration_number",),
            digits_only=True,
            value_index=7,
        ),
        XmlCellRule(
            "foreign_registration_digit_9",
            0,
            17,
            29,
            record_keys=("foreign_registration_number",),
            digits_only=True,
            value_index=8,
        ),
        XmlCellRule(
            "foreign_registration_digit_10",
            0,
            17,
            31,
            record_keys=("foreign_registration_number",),
            digits_only=True,
            value_index=9,
        ),
        XmlCellRule(
            "foreign_registration_digit_11",
            0,
            17,
            33,
            record_keys=("foreign_registration_number",),
            digits_only=True,
            value_index=10,
        ),
        XmlCellRule(
            "foreign_registration_digit_12",
            0,
            17,
            35,
            record_keys=("foreign_registration_number",),
            digits_only=True,
            value_index=11,
        ),
        XmlCellRule(
            "foreign_registration_digit_13",
            0,
            17,
            38,
            record_keys=("foreign_registration_number",),
            digits_only=True,
            value_index=12,
        ),
        XmlCellRule("passport_number", 0, 18, 3),
        XmlCellRule("passport_issue_date", 0, 18, 24),
        XmlCellRule("passport_expiry_date", 0, 18, 44),
        XmlCellRule("address_in_korea", 0, 19, 3),
        XmlCellRule("telephone", 0, 20, 8),
        XmlCellRule(
            "cell_phone",
            0,
            20,
            39,
            record_keys=("worker.phone",),
        ),
        XmlCellRule("home_country_address", 0, 21, 8),
        XmlCellRule("home_country_phone", 0, 21, 45),
        XmlCellRule(
            "school_non_school_ko",
            0,
            22,
            2,
            "checkbox",
            marker="[ ]",
            replacement_format="[v]",
            record_keys=("school_non_school",),
            text_index=3,
        ),
        XmlCellRule(
            "school_non_school_en",
            0,
            22,
            2,
            "checkbox",
            marker="[ ]",
            replacement_format="[v]",
            record_keys=("school_non_school",),
            text_index=7,
        ),
        XmlCellRule("school_name", 0, 22, 32),
        XmlCellRule("school_phone", 0, 22, 45),
        XmlCellRule(
            "current_workplace",
            0,
            24,
            12,
            record_keys=("company.name",),
        ),
        XmlCellRule("current_business_number", 0, 24, 30),
        XmlCellRule("current_workplace_phone", 0, 24, 45),
        XmlCellRule("new_workplace", 0, 25, 12),
        XmlCellRule("new_business_number", 0, 25, 30),
        XmlCellRule("new_workplace_phone", 0, 25, 45),
        XmlCellRule("annual_income", 0, 26, 12, "prepend"),
        XmlCellRule("occupation", 0, 26, 45),
        XmlCellRule("reentry_period", 0, 27, 12),
        XmlCellRule(
            "email",
            0,
            27,
            30,
            record_keys=("worker.email",),
        ),
        XmlCellRule("refund_bank_account", 0, 28, 30),
        XmlCellRule("application_date", 0, 29, 12),
        XmlCellRule(
            "applicant_signature_name",
            0,
            29,
            41,
            record_keys=("worker.legal_name",),
        ),
        XmlCellRule(
            "consent_applicant_name",
            0,
            34,
            1,
            record_keys=("worker.legal_name",),
        ),
    ),
    "standard_labor_contract_v6": (
        XmlCellRule(
            "enterprise_name",
            0,
            4,
            1,
            "append",
            record_keys=("company.name",),
        ),
        XmlCellRule("enterprise_phone", 0, 4, 3, "append"),
        XmlCellRule("enterprise_address", 0, 5, 1, "append"),
        XmlCellRule("employer_name", 0, 6, 1, "append"),
        XmlCellRule("business_number", 0, 6, 3, "append"),
        XmlCellRule(
            "employee_name",
            0,
            8,
            1,
            "append",
            record_keys=("worker.legal_name",),
        ),
        XmlCellRule("employee_birthdate", 0, 8, 3, "append"),
        XmlCellRule("employee_home_address", 0, 9, 1, "append"),
        XmlCellRule(
            "contract_start_date_ko",
            0,
            11,
            2,
            "replace",
            marker="년   월   일 ~",
            replacement_format="{value} ~",
            record_keys=("worker.contract_start",),
        ),
        XmlCellRule(
            "contract_end_date_ko",
            0,
            11,
            2,
            "replace",
            marker="년   월   일",
            replacement_format="{value}",
            record_keys=("worker.contract_end",),
        ),
        XmlCellRule(
            "probation_not_used_ko",
            0,
            11,
            2,
            "checkbox",
            marker="[ ]미활용",
            replacement_format="[v]미활용",
            record_keys=("probation_not_used",),
        ),
        XmlCellRule(
            "contract_start_date_en",
            0,
            12,
            2,
            "replace",
            marker="(   YY/MM/DD)",
            replacement_format="({value})",
            record_keys=("worker.contract_start",),
        ),
        XmlCellRule(
            "contract_end_date_en",
            0,
            12,
            2,
            "replace",
            marker="(  YY/MM/DD)",
            replacement_format="({value})",
            record_keys=("worker.contract_end",),
        ),
        XmlCellRule(
            "probation_not_used_en",
            0,
            12,
            2,
            "checkbox",
            marker="[ ] Not included",
            replacement_format="[v] Not included",
            record_keys=("probation_not_used",),
        ),
        XmlCellRule(
            "place_of_employment_ko",
            0,
            13,
            2,
            "prepend_line",
            record_keys=("enterprise_address",),
        ),
        XmlCellRule(
            "place_of_employment_en",
            0,
            14,
            2,
            "prepend_line",
        ),
        XmlCellRule(
            "industry",
            0,
            15,
            2,
            "replace",
            marker="- 업종:",
            replacement_format="- 업종: {value}",
        ),
        XmlCellRule(
            "business_description",
            0,
            15,
            2,
            "replace",
            marker="- 사업내용:",
            replacement_format="- 사업내용: {value}",
        ),
        XmlCellRule(
            "job_description",
            0,
            15,
            2,
            "replace",
            marker="- 직무내용:",
            replacement_format="- 직무내용: {value}",
        ),
        XmlCellRule(
            "industry_en",
            0,
            16,
            2,
            "replace",
            marker="- Industry:",
            replacement_format="- Industry: {value}",
        ),
        XmlCellRule(
            "business_description_en",
            0,
            16,
            2,
            "replace",
            marker="- Business description:",
            replacement_format="- Business description: {value}",
        ),
        XmlCellRule(
            "job_description_en",
            0,
            16,
            2,
            "replace",
            marker="- Job description:",
            replacement_format="- Job description: {value}",
        ),
        XmlCellRule(
            "work_start_time_ko",
            0,
            17,
            2,
            "replace",
            marker="    시    분  ~",
            replacement_format="{value} ~",
            record_keys=("work_start_time",),
        ),
        XmlCellRule(
            "work_end_time_ko",
            0,
            17,
            2,
            "replace",
            marker="시    분",
            replacement_format="{value}",
            record_keys=("work_end_time",),
        ),
        XmlCellRule(
            "daily_overtime_hours_ko",
            0,
            17,
            2,
            "replace",
            marker="1일 평균 시간외 근로시간:    시간",
            replacement_format="1일 평균 시간외 근로시간: {value}시간",
            record_keys=("daily_overtime_hours",),
        ),
        XmlCellRule(
            "daily_overtime_limit_ko",
            0,
            17,
            2,
            "replace",
            marker="변동 가능:       시간 이내)",
            replacement_format="변동 가능: {value}시간 이내)",
            record_keys=("daily_overtime_limit",),
        ),
        XmlCellRule(
            "day_shift_other_ko",
            0,
            17,
            2,
            "checkbox",
            marker="[ ]기타)",
            replacement_format="[v]기타(주간근무)",
            record_keys=("day_shift",),
        ),
        XmlCellRule(
            "work_start_time_en",
            0,
            18,
            2,
            "replace",
            marker="from (         )",
            replacement_format="from ({value})",
            record_keys=("work_start_time",),
        ),
        XmlCellRule(
            "work_end_time_en",
            0,
            18,
            2,
            "replace",
            marker="to (         )",
            replacement_format="to ({value})",
            record_keys=("work_end_time",),
        ),
        XmlCellRule(
            "daily_overtime_hours_en",
            0,
            18,
            2,
            "replace",
            marker="average daily over time:      hours",
            replacement_format="average daily over time: {value} hours",
            record_keys=("daily_overtime_hours",),
        ),
        XmlCellRule(
            "daily_overtime_limit_en",
            0,
            18,
            2,
            "replace",
            marker="up to       hour(s))",
            replacement_format="up to {value} hour(s))",
            record_keys=("daily_overtime_limit",),
        ),
        XmlCellRule(
            "day_shift_other_en",
            0,
            18,
            2,
            "checkbox",
            marker="[ ]etc.)",
            replacement_format="[v]etc. (day shift)",
            record_keys=("day_shift",),
        ),
        XmlCellRule(
            "recess_minutes_ko",
            0,
            19,
            2,
            "replace",
            marker="1일      분",
            replacement_format="1일 {value}분",
            record_keys=("recess_minutes",),
        ),
        XmlCellRule(
            "recess_minutes_en",
            0,
            20,
            2,
            "replace",
            marker="(     ) minutes per day",
            replacement_format="({value}) minutes per day",
            record_keys=("recess_minutes",),
        ),
        XmlCellRule(
            "holiday_sunday_ko",
            0,
            21,
            2,
            "checkbox",
            marker="[ ]일요일",
            replacement_format="[v]일요일",
            record_keys=("holiday_sunday",),
        ),
        XmlCellRule(
            "holiday_legal_ko",
            0,
            21,
            2,
            "checkbox",
            marker="[ ]공휴일",
            replacement_format="[v]공휴일",
            record_keys=("holiday_legal",),
        ),
        XmlCellRule(
            "holiday_legal_paid_ko",
            0,
            21,
            2,
            "checkbox",
            marker="[ ]유급",
            replacement_format="[v]유급",
            record_keys=("holiday_legal_paid",),
        ),
        XmlCellRule(
            "holiday_every_saturday_ko",
            0,
            21,
            2,
            "checkbox",
            marker="[ ]매주 토요일",
            replacement_format="[v]매주 토요일",
            record_keys=("holiday_every_saturday",),
        ),
        XmlCellRule(
            "holiday_sunday_en",
            0,
            22,
            2,
            "checkbox",
            marker="[ ]Sunday",
            replacement_format="[v]Sunday",
            record_keys=("holiday_sunday",),
        ),
        XmlCellRule(
            "holiday_legal_en",
            0,
            22,
            2,
            "checkbox",
            marker="[ ]Legal holiday",
            replacement_format="[v]Legal holiday",
            record_keys=("holiday_legal",),
        ),
        XmlCellRule(
            "holiday_legal_paid_en",
            0,
            22,
            2,
            "checkbox",
            marker="[ ]Paid",
            replacement_format="[v]Paid",
            record_keys=("holiday_legal_paid",),
        ),
        XmlCellRule(
            "holiday_every_saturday_en",
            0,
            22,
            2,
            "checkbox",
            marker="[ ]Every saturday",
            replacement_format="[v]Every saturday",
            record_keys=("holiday_every_saturday",),
        ),
        XmlCellRule(
            "monthly_normal_wage_ko",
            1,
            1,
            1,
            "replace",
            marker="1) 월 통상임금       (          )원",
            replacement_format="1) 월 통상임금 ({value})원",
            record_keys=("monthly_normal_wage",),
        ),
        XmlCellRule(
            "basic_pay_ko",
            1,
            1,
            1,
            "replace",
            marker=" - 기본급[(월, 시간, 일, 주)급]   (           )원  ",
            replacement_format=" - 기본급[(월)급] ({value})원  ",
            record_keys=("basic_pay",),
        ),
        XmlCellRule(
            "fixed_allowances_ko",
            1,
            1,
            1,
            "replace",
            marker=(
                " - 고정적 수당: (        수당 :         원), "
                "(        수당:          원)"
            ),
            replacement_format=" - 고정적 수당: {value}",
            record_keys=("fixed_allowances",),
        ),
        XmlCellRule(
            "bonus_ko",
            1,
            1,
            1,
            "replace",
            marker=" - 상여금 (          원)",
            replacement_format=" - 상여금 ({value}원)",
            record_keys=("bonus",),
        ),
        XmlCellRule(
            "monthly_normal_wage_en",
            1,
            2,
            1,
            "replace",
            marker="1) Monthly Normal wages     (          )won",
            replacement_format="1) Monthly Normal wages ({value}) won",
            record_keys=("monthly_normal_wage",),
        ),
        XmlCellRule(
            "basic_pay_en",
            1,
            2,
            1,
            "replace",
            marker=(
                " - Basic pay[(Monthly, hourly, daily, weekly) wage]  "
                "(            )won"
            ),
            replacement_format=" - Basic pay[(Monthly) wage] ({value}) won",
            record_keys=("basic_pay",),
        ),
        XmlCellRule(
            "fixed_allowances_en",
            1,
            2,
            1,
            "replace",
            marker=(
                " - Fixed benefits: (      benefits :        )won, "
                "(     benefits :       )won"
            ),
            replacement_format=" - Fixed benefits: {value}",
            record_keys=("fixed_allowances_en",),
        ),
        XmlCellRule(
            "bonus_en",
            1,
            2,
            1,
            "replace",
            marker=" - Bonus: (            )won",
            replacement_format=" - Bonus: {value} won",
            record_keys=("bonus",),
        ),
        XmlCellRule(
            "payment_day_ko",
            1,
            3,
            1,
            "replace",
            marker="매월 (     )일",
            replacement_format="매월 ({value})일",
            record_keys=("payment_day",),
        ),
        XmlCellRule(
            "payment_day_en",
            1,
            4,
            1,
            "replace",
            marker="Every (        )th",
            replacement_format="Every ({value})th",
            record_keys=("payment_day",),
        ),
        XmlCellRule(
            "payment_bank_transfer_ko",
            1,
            5,
            1,
            "checkbox",
            marker="[  ]통장 입금",
            replacement_format="[v]통장 입금",
            record_keys=("payment_bank_transfer",),
        ),
        XmlCellRule(
            "payment_bank_transfer_en",
            1,
            6,
            1,
            "checkbox",
            marker="[  ]By direct deposit transfer into the employee's account",
            replacement_format=(
                "[v]By direct deposit transfer into the employee's account"
            ),
            record_keys=("payment_bank_transfer",),
        ),
        XmlCellRule(
            "accommodation_provided_ko",
            1,
            7,
            1,
            "checkbox",
            marker="[  ]제공",
            replacement_format="[v]제공",
            record_keys=("accommodation_provided",),
        ),
        XmlCellRule(
            "accommodation_business_building_ko",
            1,
            7,
            1,
            "checkbox",
            marker="[ ]사업장 건물",
            replacement_format="[v]사업장 건물",
            record_keys=("accommodation_business_building",),
        ),
        XmlCellRule(
            "accommodation_cost_ko",
            1,
            7,
            1,
            "replace",
            marker=" - 숙박시설 제공 시 근로자 부담금액: 매월        원",
            replacement_format=(
                " - 숙박시설 제공 시 근로자 부담금액: 매월 {value}원"
            ),
            record_keys=("accommodation_cost",),
        ),
        XmlCellRule(
            "meal_lunch_ko",
            1,
            7,
            1,
            "checkbox",
            marker="[  ]중식",
            replacement_format="[v]중식",
            record_keys=("meal_lunch",),
        ),
        XmlCellRule(
            "meal_cost_ko",
            1,
            7,
            1,
            "replace",
            marker=" - 식사 제공 시 근로자 부담금액: 매월        원",
            replacement_format=" - 식사 제공 시 근로자 부담금액: 매월 {value}원",
            record_keys=("meal_cost",),
        ),
        XmlCellRule(
            "accommodation_provided_en",
            1,
            9,
            1,
            "checkbox",
            marker="[  ]Provided",
            replacement_format="[v]Provided",
            record_keys=("accommodation_provided",),
            text_index=2,
        ),
        XmlCellRule(
            "accommodation_business_building_en",
            1,
            9,
            1,
            "checkbox",
            marker="[  ]Rooms within the business building",
            replacement_format="[v]Rooms within the business building",
            record_keys=("accommodation_business_building",),
        ),
        XmlCellRule(
            "accommodation_cost_en",
            1,
            9,
            1,
            "replace",
            marker="         won/month",
            replacement_format=" {value} won/month",
            record_keys=("accommodation_cost",),
            text_index=22,
        ),
        XmlCellRule(
            "meal_provided_en",
            1,
            9,
            1,
            "checkbox",
            marker="[  ]",
            replacement_format="[v]",
            record_keys=("meal_provided",),
            text_index=25,
        ),
        XmlCellRule(
            "meal_lunch_en",
            1,
            9,
            1,
            "checkbox",
            marker="[  ]",
            replacement_format="[v]",
            record_keys=("meal_lunch",),
            text_index=29,
        ),
        XmlCellRule(
            "meal_cost_en",
            1,
            9,
            1,
            "replace",
            marker=" - Cost of meals paid by employee:        won/month",
            replacement_format=(
                " - Cost of meals paid by employee: {value} won/month"
            ),
            record_keys=("meal_cost",),
        ),
        XmlCellRule(
            "contract_date",
            1,
            15,
            0,
            "replace",
            marker="년        월        일",
            replacement_format="{value}",
        ),
        XmlCellRule(
            "signature_employer_name_ko",
            1,
            15,
            0,
            "replace",
            marker="     사용자:                          ",
            replacement_format="     사용자: {value}",
            record_keys=("employer_name",),
        ),
        XmlCellRule(
            "signature_employer_name_en",
            1,
            15,
            0,
            "replace",
            marker="Employer:                          ",
            replacement_format="Employer: {value}",
            record_keys=("employer_name_en",),
        ),
        XmlCellRule(
            "signature_employee_name_ko",
            1,
            15,
            0,
            "replace",
            marker="     근로자:                          ",
            replacement_format="     근로자: {value}",
            record_keys=("worker.legal_name",),
        ),
        XmlCellRule(
            "signature_employee_name_en",
            1,
            15,
            0,
            "replace",
            marker="Employee:                          ",
            replacement_format="Employee: {value}",
            record_keys=("worker.legal_name",),
        ),
    ),
}


__all__ = ["TEMPLATE_RULES", "CellOperation", "XmlCellRule"]
